"""empty message

Revision ID: 73a49fa950dd
Revises: ecc0fde59a3a
Create Date: 2023-04-17 14:07:14.463332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a49fa950dd'
down_revision = 'ecc0fde59a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=400), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
